### ISSUE TITLE
pp (pretty print) not working

### ISSUE THREAD

**Issue by synic** [pdbpp/pdbpp#397] opened 2020-04-15 22:23 UTC
`pdbpp==0.10.2`
`Python 3.8.0`

I can't get `pp` to do anything but return:

```
(Pdb++) data = {1, 2}
(Pdb++) pp data
(Pdb++) pp data
(Pdb++) print(data)
{1, 2}
(Pdb++) pp(data)
(Pdb++)
```

**Comment by noelevans** [comment] 2020-05-24 20:43
I'm struggling to reproduce this. I have tried with freshly updated source and pdbpp 0.10.2 release. I've used python 3.8.2 but am struggling to setup 3.8.0. It seems hard to imagine this is the problem. 

I'm using ubuntu 20.20. Are there any other specifics to your setup?

**Comment by noelevans** [comment] 2020-05-25 19:45
I've tested with 3.8.0 too and don't see this problem

**Comment by blueyed** [comment] 2021-04-07 22:53
@morotti do you see this issue yourself? (since you've mentioned it in #442)

I cannot reproduce it either:
```
% python -m pdb t-pdb.py
…
(Pdb++) pp 12
12
(Pdb++) pp
*** SyntaxError: unexpected EOF while parsing
(Pdb++) help pp
pp expression
        Pretty-print the value of the expression.
```
@synic please try the `pp` and `help pp` commands/lines to see if `pp` is what you're expecting.. check `alias` maybe to see if it is in there maybe.

**Comment by blueyed** [comment] 2021-05-06 21:33
Needs more info, closing.

**Closed as completed by blueyed** 2021-05-06 21:33 UTC
Labels: bug, needs info
