### ISSUE TITLE
pdbpp doesn't exit the debugger

### ISSUE THREAD

**Issue by rghelichi** [pdbpp/pdbpp#399] opened 2020-05-14 19:59 UTC
(pdbpp==0.10.2)

It happened few times. I start the run by 
python -m pdb myfile.py
(pdb++) c

then after debugging the code in sticky mode 
it doesn't exit the code and I have to close the terminal 
I have tried with q, c, !!c, cntrl+c 
and none of them works

**Comment by noelevans** [comment] 2020-05-24 20:47
Do you have a simple script that demonstrates this? Using pdbpp==0.10.2 I don't get this behaviour following the desciption

**Comment by rghelichi** [comment] 2020-05-26 14:58
It gets stuck in pdb.py at line 1545 and I keep pushing "q" and it doesn't quit.

**Comment by blueyed** [comment] 2020-08-28 23:15
This needs more information.  pdb.py on tag 0.10.2 only has 1301 lines, so this might be Python's pdb.py then?
Anyway, a way to reproduce this is needed (also providing the Python version then).  You can also try master, since there are many changes there already.

**Comment by blueyed** [comment] 2020-11-09 03:15
Closing as per previous comment for now - needs more information/details.

**Closed as completed by blueyed** 2020-11-09 03:15 UTC
Labels: bug
