### ISSUE TITLE
Installing pdbpp causes ipdb to error on specific commands like `up`

### ISSUE THREAD

**Issue by nathanielatom** [pdbpp/pdbpp#430] opened 2020-12-10 21:34 UTC
Code snippet in ipython:

```
In [1]: def foo(): 
   ...:     return bar() 
   ...:                                                                                                                                        

In [2]: def bar(): 
   ...:     raise TypeError 
   ...:                                                                                                                                        

In [3]: foo()
```

then to start post-mortem debugging
```
In [4]: %debug
```

which mostly works, except when running the `up` command:
```
ipdb> up                                                                                                                                       
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
TypeError: 'list' object is not callable
```

There's more info, including the full traceback, in the other issues:
https://github.com/gotcha/ipdb/issues/210
https://github.com/ipython/ipython/issues/12721

pdbpp v0.10.2
ipdb v0.13.4
ipython v7.19.0
python v3.7.6

**Comment by blueyed** [comment] 2020-12-10 21:46
Duplicate of https://github.com/pdbpp/pdbpp/issues/408, fixed in master.
Might be worth creating a bugfix release for it, but given many changes in master already that might not be trivial.
Using master for now is recommended anyway.

**Closed as completed by blueyed** 2020-12-10 21:46 UTC

**Comment by nathanielatom** [comment] 2020-12-10 23:34
Thanks! Sorry I didn't catch that one, looked for `ipdb` and `up`.
