### ISSUE TITLE
Namespace confusion

### ISSUE THREAD

**Issue by technillogue** [pdbpp/pdbpp#266] opened 2019-07-31 13:46 UTC
(CPython) PDB's usual `default` exec() behavior handles namespaces in very confusing ways

Consider the following program:
```
spam = "global"

def func():
    eggs = "local"
    shopping = ["eggs"]
    breakpoint()
    print(eggs)
    print(shopping)
    print(ham)

func()
```

1. Restrictive class namespace rules
```
-> print(eggs)
(Pdb++) [spam for i in range(2)]
['global', 'global']
(Pdb++) [eggs for i in range(2)]
*** NameError: name 'eggs' is not defined
```

This happens because PDB passes globals and locals and "If exec gets two separate objects as globals and locals, the code will be executed as if it were embedded in a class definition."

2. Confusing f_locals behavior

a)
```
-> print(ham)
(Pdb++) ham = "set from pdb"
(Pdb++) print(ham)
set from pdb
(Pdb++) s
NameError: name 'ham' is not defined
```

b) 
```
[1] > .*(7)func()
-> print(eggs)
(Pdb++) ham = "set from pdb"
(Pdb++) print(ham)
set from pdb
(Pdb++) step
local
[1] > .*(8)func()
-> print(shopping)
(Pdb++) s
['eggs']
[1] > .*(9)func()
-> print(ham)
(Pdb++) print(ham)
set from pdb
(Pdb++) s
NameError: name 'ham' is not defined
```

c)
```
(Pdb++) eggs = "redefined from pdb"
(Pdb++) print(eggs)
changed from pdb
(Pdb++) step
local
[1] > .*(8)func()
-> print(shopping)
(Pdb++) print(eggs)
local
```

d)
```
-> print(eggs)
(Pdb++) del eggs
(Pdb++) print(eggs)
*** NameError: name 'eggs' is not defined
(Pdb++) s
local
[1] > .*(8)func()
-> print(shopping)
(Pdb++) print(eggs)
local
```

e) a counterexample

```
-> print(shopping)
(Pdb++) shopping.append("appended from pdb")
(Pdb++) print(shopping)
['eggs', 'appended from pdb']
(Pdb++) step
['eggs', 'appended from pdb']
```

**Comment by technillogue** [comment] 2019-07-31 13:47
I have a fix for this in my own .pdbrc.py, I'll try to get a PR in soon, but have been struggling to get tox to work. I think I have to write my PR against the last release, because the most recent commit doesn't pass the tests.

**Comment by technillogue** [comment] 2019-07-31 13:48
(I've also been uncertain where to talk to maintainers ― IRC is fine, but I didn't get a response in #pypy )

**Comment by blueyed** [comment] 2019-07-31 14:30
> IRC is fine, but I didn't get a response in #pypy

You were not online anymore when I've tried to reply.. ;)
I think GitHub issues is fine - otherwise query me directly on IRC, or create a `#pdbpp` channel.

You should use master for PRs - the last release is old.
What is the problem with `tox -e py37`?
In general it should also work to create a virtualenv, and run pytest directly:
```
% git clone https://github.com/pdbpp/pdbpp
% cd pdbpp
% python -m venv .venv
% source .venv/bin/activate
% pip install '.[testing]'
% pytest
```
I see that `test_python_m_pdb_uses_pdbpp` is failing - will look into it.

As for new features / tests: you can just run those tests then, e.g. using `pytest -k` etc of course.

**Comment by blueyed** [comment] 2019-07-31 14:34
Otherwise I'm interested in a fix for this of course.
Given that you have the examples already, you can hopefully turn those into tests easily.
It might take a bit of learning, but in general the tests are OK to write, based on existing examples.

**Comment by technillogue** [comment] 2019-07-31 17:03
Master has seven failing tests with running pytest directly (last release
just has pdb_uses_pdbpp fail inexplicably). Does master change anything
about `pdb.default` though?

If using `-e py37` is okay that should work, I use a chromebook with
limited space to install every python and my usual remote server runs nixos

Dropping my version in as-is causes a bunch of tests to fail, it'll take me
a while to figure out.

**Comment by blueyed** [comment] 2019-07-31 17:53
> Master has seven failing tests with running pytest directly (last release
just has pdb_uses_pdbpp fail inexplicably).

Can you provide more information?
Are you using a virtualenv, with fancycompleter master etc (`pip install .`)?

> If using `-e py37` is okay that should work

Sure, I usually also test with py37 only (although not even via tox then normally).  There is CI to test the other variants.

> Dropping my version in as-is causes a bunch of tests to fail, it'll take me
a while to figure out.

You could create a WIP with it already.
Do you know around with pytest?  Given the project itself, you usually want to use e.g. `--pdbcls pdb:pdb.Pdb`, but it is often still problematic to debug tests using this.
I often create a separate file for the test itself and then run it live to see what is happening and/or to have breakpoints there then.
And given the nature of the tests themselves, print-debugging works quite well there also - since it compares expected output / commands (but gets out of sync with the first extra print then..).

**Comment by blueyed** [comment] 2019-07-31 17:58
btw: given the issue(s) you are fixing there it might well be that there are existing tests that behave differently now, and just need to be adjusted, of course.
Having a PR would allow to discuss it on the code already.. :)

**Comment by technillogue** [comment] 2019-07-31 22:12
Here's just the first change, it has four failing tests that I don't really understand, do you want an actual PR? https://github.com/technillogue/pdbpp

**Comment by blueyed** [comment] 2019-07-31 23:36
I would a separate branch for it to start with.
I am not sure globals/locals should be merged like this, and the failing tests appear to show it.
E.g.with `test_locals`: setting `foo = 42` does not make it available later then.
And changing an existing one keeps the old value:
```
-> __import__('pdb').set_trace()
(Pdb++) innervar
42
(Pdb++) innervar = 43
(Pdb++) innervar
42
(Pdb++) l
  1     def func():
  2         innervar = 42  # noqa: F841
  3  ->     __import__('pdb').set_trace()
  4
  5
  6     func()
[EOF]
```
I think it would be good to have a test for what you are trying to fix here to begin with.

**Comment by blueyed** [comment] 2019-07-31 23:42
It appears to be a problem with `curframe_locals` after all if I understand it correctly, and pdb itself is affected by this already (i.e. not an issue/regression with pdb++), right?
IIRC there is some discussion / issue about this in the Python issue tracker, and it should be investigated why curframe_locals is handled like that already (IIRC it is because how Python handles locals internally - and this might just be incomplete for list comprehensions then).
There might be done some work to improve this already (patch / pending PR for cpython).

**Comment by blueyed** [comment] 2019-07-31 23:54
Maybe the pattern from `do_interact` could be used?  https://github.com/pdbpp/pdbpp/blob/0b3e62a7fdd5d7c560fd0dc1165c205926986456/pdb.py#L1019-L1028  (but it is also not using `exec` (directly)).

**Comment by blueyed** [comment] 2019-08-01 00:23
Here might be a patch, this issue is "won't fix" though: https://bugs.python.org/issue21161

The patch from there appears to work (on top of your master branch):
```diff
diff --git i/pdb.py w/pdb.py
index aa62a3e..1c67d7d 100644
--- i/pdb.py
+++ w/pdb.py
@@ -697,8 +697,8 @@ def default(self, line):
         self.history.append(line)
         if line[:1] == '!': line = line[1:]
         locals = self.curframe_locals
-        globals = self.curframe.f_globals
-        namespace = {**globals, **locals}
+        ns = self.curframe.f_globals.copy()
+        ns.update(locals)
         try:
             code = compile(line + '\n', '<stdin>', 'single')
             save_stdout = sys.stdout
@@ -708,7 +708,7 @@ def default(self, line):
                 sys.stdin = self.stdin
                 sys.stdout = self.stdout
                 sys.displayhook = self.displayhook
-                exec(code, namespace)
+                exec(code, ns, locals)
             finally:
                 sys.stdout = save_stdout
                 sys.stdin = save_stdin
```

**Comment by blueyed** [comment] 2019-08-01 05:36
Used in https://github.com/pdbpp/pdbpp/pull/268.

**Comment by blueyed** [comment] 2019-08-01 19:13
@technillogue 
Does https://github.com/pdbpp/pdbpp/pull/268 work for you?
Does it fix / address all of the issues here?

**Closed as completed** 2019-08-13 17:11 UTC
Labels: bug
